"""Summarise the load-test runs for one label into Markdown for the results record.

Usage (from load_test/):
    python summarise_runs.py llama1b-15m --duration 900

Reads results/<label>_run<N>.jtl and logs/<label>_run<N>_requests.jsonl for every run
found, and prints:
  - one table row per run, then Mean and Spread (min-max) rows,
  - sample standard deviations across runs,
  - a reconciliation table: JMeter request count vs SUT log lines for that X-Run-ID.

Percentiles use the nearest-rank method (same as run_model.ps1): the value at
position ceil(p/100 * n) in the sorted list. A failed request counts in n and in
the latency percentiles with the elapsed time JMeter recorded for it.
"""
import argparse
import csv
import glob
import json
import math
import os
import re
import statistics
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def pct(values, p):
    if not values:
        return None
    s = sorted(values)
    return s[min(len(s) - 1, math.ceil(p / 100 * len(s)) - 1)]


def run_stats(jtl_path, duration):
    with open(jtl_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    by = {}
    for r in rows:
        by.setdefault(r["label"], []).append(r)
    post = by.get("POST /tickets", [])
    search = by.get("GET /search", [])
    stats = by.get("GET /stats", [])
    post_ms = [int(r["elapsed"]) for r in post]
    post_err = sum(r["success"] != "true" for r in post)
    all_err = sum(r["success"] != "true" for r in rows)
    return {
        "total": len(rows),
        "post_n": len(post),
        "post_err": post_err,
        "p50": pct(post_ms, 50),
        "p95": pct(post_ms, 95),
        "p99": pct(post_ms, 99),
        "search_n": len(search),
        "search_p95": pct([int(r["elapsed"]) for r in search], 95),
        "stats_n": len(stats),
        "all_err": all_err,
        "err_rate": all_err / len(rows) if rows else 0.0,
        # successful classifications per hour, over the configured run length
        "post_per_hr": (len(post) - post_err) * 3600 / duration,
    }


def log_counts(log_path, run_id):
    """Count SUT log lines for this exact X-Run-ID, split by route, plus models seen."""
    if not os.path.exists(log_path):
        return None
    n, post, digests = 0, 0, set()
    with open(log_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if rec.get("run_id") != run_id:
                continue
            n += 1
            if rec.get("route") == "/tickets" and rec.get("method") == "POST":
                post += 1
            if rec.get("model_digest"):
                digests.add((rec.get("model"), rec["model_digest"][:12]))
    return {"lines": n, "post": post, "models": sorted(digests)}


def fmt(v, nd=0):
    if v is None:
        return "-"
    if isinstance(v, float) and nd:
        return f"{v:.{nd}f}"
    return f"{round(v):d}" if isinstance(v, float) else str(v)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("label")
    ap.add_argument("--duration", type=int, default=900, help="configured run length in seconds")
    ap.add_argument("--out", help="also write the Markdown to this file (UTF-8)")
    ap.add_argument("--record", help="results record to update between <!-- BEGIN/END label --> markers")
    a = ap.parse_args()

    jtls = glob.glob(os.path.join(HERE, "results", f"{a.label}_run*.jtl"))
    runs = []
    for p in jtls:
        m = re.search(r"_run(\d+)\.jtl$", p)
        if m:
            runs.append((int(m.group(1)), p))
    runs.sort()
    if not runs:
        sys.exit(f"no results/{a.label}_run*.jtl found")

    out = []
    out.append(f"<!-- generated by load_test/summarise_runs.py {a.label} --duration {a.duration} -->")
    out.append("| Run | Run ID | POST n | POST err | POST p50 | POST p95 | POST p99 | Successful POST/hr | Search n | Search p95 | Stats n | Overall error rate |")
    out.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    S, recon = [], []
    for n, p in runs:
        run_id = f"{a.label}-run{n}"
        s = run_stats(p, a.duration)
        S.append(s)
        out.append(
            f"| {n} | `{run_id}` | {s['post_n']} | {s['post_err']} | {fmt(s['p50'])} | {fmt(s['p95'])} | {fmt(s['p99'])} | "
            f"{s['post_per_hr']:.0f} | {s['search_n']} | {fmt(s['search_p95'])} | {s['stats_n']} | "
            f"{s['err_rate']:.1%} ({s['all_err']}/{s['total']}) |"
        )
        lc = log_counts(os.path.join(HERE, "logs", f"{a.label}_run{n}_requests.jsonl"), run_id)
        recon.append((run_id, s, lc))

    def col(k):
        return [s[k] for s in S if s[k] is not None]

    keys = ["post_n", "post_err", "p50", "p95", "p99", "post_per_hr", "search_n", "search_p95", "stats_n"]
    mean = {k: statistics.mean(col(k)) if col(k) else None for k in keys}
    lo = {k: min(col(k)) if col(k) else None for k in keys}
    hi = {k: max(col(k)) if col(k) else None for k in keys}
    er = [s["err_rate"] for s in S]

    def m1(k):
        v = mean[k]
        return "-" if v is None else (f"{v:.0f}" if float(v).is_integer() else f"{v:.1f}")

    out.append(
        f"| Mean | | {m1('post_n')} | {m1('post_err')} | {m1('p50')} | {m1('p95')} | {m1('p99')} | {m1('post_per_hr')} | "
        f"{m1('search_n')} | {m1('search_p95')} | {m1('stats_n')} | {statistics.mean(er):.1%} |"
    )

    def r(k):
        return "-" if lo[k] is None else f"{lo[k]:.0f}–{hi[k]:.0f}"

    out.append(
        f"| Spread (min–max) | | {r('post_n')} | {r('post_err')} | {r('p50')} | {r('p95')} | {r('p99')} | {r('post_per_hr')} | "
        f"{r('search_n')} | {r('search_p95')} | {r('stats_n')} | {min(er):.1%}–{max(er):.1%} |"
    )
    out.append("")
    if len(S) >= 2:
        sd = lambda k: f"{statistics.stdev(col(k)):.1f}" if len(col(k)) >= 2 else "-"
        out.append(
            f"Sample standard deviation across the {len(S)} runs: p50 {sd('p50')} ms, p95 {sd('p95')} ms, "
            f"p99 {sd('p99')} ms, search p95 {sd('search_p95')} ms."
        )
        out.append("")

    out.append("Reconciliation (JMeter `.jtl` vs SUT `requests.jsonl`, matched by exact `X-Run-ID`; the separate `warmup-` line is excluded):")
    out.append("")
    out.append("| Run ID | JMeter requests | SUT log lines | JMeter POST | SUT log POST | Model (digest) | Match |")
    out.append("|---|---:|---:|---:|---:|---|---|")
    for run_id, s, lc in recon:
        if lc is None:
            out.append(f"| `{run_id}` | {s['total']} | log missing | {s['post_n']} | - | - | NO |")
            continue
        ok = lc["lines"] == s["total"] and lc["post"] == s["post_n"] and len(lc["models"]) == 1
        models = ", ".join(f"{m} ({d})" for m, d in lc["models"]) or "-"
        out.append(
            f"| `{run_id}` | {s['total']} | {lc['lines']} | {s['post_n']} | {lc['post']} | {models} | {'yes' if ok else 'NO'} |"
        )
    text = "\n".join(out) + "\n"
    sys.stdout.reconfigure(encoding="utf-8")
    print(text, end="")
    if a.out:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(text)
    if a.record:
        # Replace everything between <!-- BEGIN label --> and <!-- END label --> in the record.
        with open(a.record, encoding="utf-8") as f:
            rec = f.read()
        begin, end = f"<!-- BEGIN {a.label} -->", f"<!-- END {a.label} -->"
        i, j = rec.find(begin), rec.find(end)
        if i < 0 or j < i:
            sys.exit(f"markers for {a.label} not found in {a.record}")
        rec = rec[: i + len(begin)] + "\n" + text + rec[j:]
        with open(a.record, "w", encoding="utf-8", newline="") as f:
            f.write(rec)
        print(f"updated {a.record} ({a.label})", file=sys.stderr)


if __name__ == "__main__":
    main()
